name: CI - Build & Push image (develop)

on:
  push:
    branches: ["develop"]   # ejecuta en cada push a develop

permissions:
  contents: read
  packages: write           # necesario para publicar en GHCR con GITHUB_TOKEN

env:
  IMAGE_NAME: ghcr.io/ivan-frias/myturn-back-api

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # runner efímero que pone GitHub

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR with GITHUB_TOKEN
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}   # token automático del workflow

      # (Opcional) leer versión del pom para etiquetar
      - name: Set up Temurin JDK 21 (to read pom version)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Read Maven project version
        run: echo "VERSION=$(mvn -q -DforceStdout -Dexpression=project.version help:evaluate)" >> $GITHUB_ENV

      - name: Build & push image to GHCR
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest-develop
            ${{ env.IMAGE_NAME }}:develop-${{ github.sha }}
            ${{ env.IMAGE_NAME }}:${{ env.VERSION }}
